[package]
name = "modbot"
version = "0.4.8"
description = """Discord bot for https://mod.io.
ModBot provides commands to search for mods and notifications about added & edited mods."""
readme = "README.md"
repository = "https://github.com/nickelc/modio-bot"
license = "MIT/Apache-2.0"
authors = ["Constantin Nickel <constantin.nickel@gmail.com>"]
keywords = ["modio", "discord", "bot"]
edition = "2021"
rust-version = "1.60.0"
include = ["src/**/*.rs", "LICENSE-*", "README.md", "build.rs", "migrations"]

[dependencies]
bitflags = "1"
bytesize = "1"
csv = "1.1"
dbl-rs = "0.3"
dotenv = "0.15"
futures-core = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = { version = "0.14", features = ["server"] }
kuchiki = "0.8"
pico-args = "0.5"
prometheus = { version = "0.13", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
time = { version = "0.3", features = ["formatting", "macros"] }
tokio = { version = "1.0", features = ["time", "full"] }
toml = "0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }

# twilight
twilight-gateway = "0.13"
twilight-http = "0.13"
twilight-model= "0.13"
twilight-cache-inmemory = "0.13"
twilight-util = { version = "0.13", features = ["builder"] }
twilight-validate = "0.13"

[dependencies.modio]
version = "0.7"
default-features = false
features = ["rustls-tls"]

[dependencies.diesel]
version = "2.0"
features = ["r2d2", "sqlite"]

[dependencies.diesel_migrations]
version = "2.0"

[dependencies.libsqlite3-sys]
version = ">=0.17.2, <0.26.0"
optional = true

[build-dependencies]
git2 = { version = "0.15", default-features = false }

[features]
sqlite-bundled = ["libsqlite3-sys/bundled"]

[profile.release]
lto = true
